# Generated by Django 5.2.8 on 2025-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_mediaitem_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='compressed_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/compressed/'),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='media',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/originals/'),
        ),
    ]
