# Generated by Django 5.2.8 on 2025-11-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_media_file_media_compressed_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='compressed_file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='original_file',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default='defaults/default.jpg', upload_to='uploads/'),
        ),
    ]
