# Generated by Django 5.2.8 on 2025-12-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_post_description_postmediatag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='media',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
            preserve_default=False,
        ),
    ]
