# Generated by Django 5.2.8 on 2025-12-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_reelwatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='avatar',
            field=models.ImageField(blank=True, default='page_avatars/default.png', null=True, upload_to='page_avatars/'),
        ),
    ]
