# Generated by Django 5.2.8 on 2025-12-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_mutedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='anyone_can_post',
            field=models.BooleanField(default=True),
        ),
    ]
