# Generated by Django 5.2.8 on 2025-12-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_conversationhidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='memories_public',
            field=models.BooleanField(default=True),
        ),
    ]
