# Generated by Django 5.2.8 on 2025-12-27 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userprofile_first_name_userprofile_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('search', 'Search'), ('direct', 'Direct'), ('link', 'Link')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visited_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='api.page')),
                ('visited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['visitor'], name='api_profile_visitor_6e397b_idx'), models.Index(fields=['visited_user'], name='api_profile_visited_854c8a_idx'), models.Index(fields=['visited_page'], name='api_profile_visited_c89fbd_idx'), models.Index(fields=['source'], name='api_profile_source_63b4ae_idx')],
            },
        ),
    ]
