# Generated by Django 5.2.8 on 2025-12-27 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_profilevisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profilevisit',
            name='api_profile_source_63b4ae_idx',
        ),
        migrations.RenameField(
            model_name='profilevisit',
            old_name='source',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='profilevisit',
            name='surface',
            field=models.CharField(choices=[('home', 'Home Feed'), ('reels', 'Reels'), ('stories', 'Stories'), ('profile', 'Profile'), ('comments', 'Comments'), ('messages', 'Messages'), ('notifications', 'Notifications'), ('explore', 'Explore')], default='home', max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='profilevisit',
            index=models.Index(fields=['channel'], name='api_profile_channel_5e4efd_idx'),
        ),
        migrations.AddIndex(
            model_name='profilevisit',
            index=models.Index(fields=['surface'], name='api_profile_surface_7a349c_idx'),
        ),
        migrations.AddIndex(
            model_name='profilevisit',
            index=models.Index(fields=['created_at'], name='api_profile_created_574493_idx'),
        ),
    ]
