# Generated by Django 5.2.8 on 2025-12-27 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_profilevisit_api_profile_source_63b4ae_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisit',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time spent on profile/page in seconds'),
        ),
        migrations.AddIndex(
            model_name='profilevisit',
            index=models.Index(fields=['duration_seconds'], name='api_profile_duratio_e5a023_idx'),
        ),
    ]
