# Generated by Django 5.2.8 on 2025-12-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_profilevisit_duration_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('search', 'Search'), ('direct', 'Direct'), ('link', 'Link')], max_length=20)),
                ('surface', models.CharField(choices=[('reels', 'Reels'), ('explore', 'Explore'), ('profile', 'Profile'), ('page', 'Page'), ('home', 'Home Feed')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Time watched in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watches', to='api.post')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['viewer'], name='api_videowa_viewer__8b3c51_idx'), models.Index(fields=['post'], name='api_videowa_post_id_170c87_idx'), models.Index(fields=['channel'], name='api_videowa_channel_a41dc2_idx'), models.Index(fields=['surface'], name='api_videowa_surface_967638_idx'), models.Index(fields=['created_at'], name='api_videowa_created_663a0d_idx'), models.Index(fields=['duration_seconds'], name='api_videowa_duratio_99302f_idx')],
            },
        ),
    ]
