# Generated by Django 5.2.8 on 2026-04-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_videowatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
