# Generated by Django 5.2.8 on 2026-04-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_postmedia_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_approved', 'Follow Approved'), ('like', 'Like'), ('comment', 'Comment'), ('comment_like', 'Comment Like'), ('mention', 'Mention')], max_length=30),
        ),
    ]
