# Generated by Django 5.2.8 on 2026-04-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_message_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='api.message')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['message'], name='api_message_message_9e1d59_idx')],
            },
        ),
    ]
