# Generated by Django 5.2.8 on 2026-04-23 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_messagemedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_approved', 'Follow Approved'), ('like', 'Like'), ('comment', 'Comment'), ('comment_like', 'Comment Like'), ('mention', 'Mention'), ('page_invite', 'Page Invite')], max_length=30),
        ),
        migrations.CreateModel(
            name='PageInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_page_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_page_invites', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.page')),
            ],
            options={
                'unique_together': {('page', 'invited_user')},
            },
        ),
    ]
