# Generated by Django 5.2.8 on 2026-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_notification_notification_type_pageinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='event_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
