# Generated by Django 5.2.8 on 2026-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_page_event_date_page_event_location_page_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_super_private',
            field=models.BooleanField(default=False),
        ),
    ]
