# Generated by Django 5.2.8 on 2026-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_page_is_super_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public_override',
            field=models.BooleanField(default=False),
        ),
    ]
