# Generated by Django 5.2.8 on 2026-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_story_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevisit',
            name='surface',
            field=models.CharField(choices=[('home', 'Home Feed'), ('reels', 'Reels'), ('profile', 'Profile'), ('comments', 'Comments'), ('messages', 'Messages'), ('notifications', 'Notifications'), ('explore', 'Explore')], max_length=20),
        ),
    ]
