# Generated by Django 5.2.8 on 2026-04-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_drop_stories_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.page'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_approved', 'Follow Approved'), ('like', 'Like'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('comment_like', 'Comment Like'), ('mention', 'Mention'), ('page_invite', 'Page Invite'), ('page_follow', 'Page Follow'), ('page_follow_request', 'Page Follow Request'), ('page_follow_approved', 'Page Follow Approved'), ('page_poster_added', 'Page Poster Added')], max_length=30),
        ),
    ]
