# Generated by Django 5.2.8 on 2026-04-29 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_notification_page_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profilevisit',
            name='api_profile_channel_5e4efd_idx',
        ),
        migrations.RemoveIndex(
            model_name='profilevisit',
            name='api_profile_surface_7a349c_idx',
        ),
        migrations.RemoveIndex(
            model_name='profilevisit',
            name='api_profile_duratio_e5a023_idx',
        ),
        migrations.RemoveIndex(
            model_name='videowatch',
            name='api_videowa_channel_a41dc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='videowatch',
            name='api_videowa_surface_967638_idx',
        ),
        migrations.RemoveIndex(
            model_name='videowatch',
            name='api_videowa_duratio_99302f_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilevisit',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videowatch',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
