# Generated by Django 5.2.8 on 2026-04-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_profilevisit_api_profile_channel_5e4efd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevisit',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time spent on profile/page in seconds'),
        ),
        migrations.AlterField(
            model_name='videowatch',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time watched in seconds'),
        ),
    ]
