# Generated by Django 5.2.8 on 2026-05-08 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_profilevisit_duration_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevisit',
            name='surface',
            field=models.CharField(choices=[('home', 'Home Feed'), ('reels', 'Reels'), ('profile', 'Profile'), ('comments', 'Comments'), ('messages', 'Messages'), ('notifications', 'Notifications'), ('explore', 'Explore'), ('search', 'Search Suggestions'), ('search_results', 'Search Results'), ('history', 'Search History')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videowatch',
            name='surface',
            field=models.CharField(choices=[('reels', 'Reels'), ('explore', 'Explore'), ('profile', 'Profile'), ('page', 'Page'), ('home', 'Home Feed'), ('search', 'Search Suggestions'), ('search_results', 'Search Results')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at', 'id'], name='post_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['page', '-created_at', 'id'], name='post_page_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at', 'id'], name='post_created_id_idx'),
        ),
    ]
