# Generated by Django 5.2.8 on 2026-05-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_user_id_3893a3_idx',
            old_name='api_activit_user_id_a1f7e3_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_user_id_8884b1_idx',
            old_name='api_activit_user_id_b2c8f4_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_action__5ec2ed_idx',
            old_name='api_activit_action__c3d9a5_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_post_id_8b4260_idx',
            old_name='api_activit_post_id_d4e0b6_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_page_id_e770e2_idx',
            old_name='api_activit_page_id_e5f1c7_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_target__f9fd57_idx',
            old_name='api_activit_target__f6a2d8_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_hashtag_b8eca1_idx',
            old_name='api_activit_hashtag_a7b3e9_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_sentime_d983ad_idx',
            old_name='api_activit_sentime_b8c4fa_idx',
        ),
    ]
