# Generated by Django 5.2.8 on 2026-05-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_page_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagechatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
