# Generated by Django 5.2.8 on 2026-05-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_page_chat_media'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagechatmessagemedia',
            new_name='api_pagecha_message_05643b_idx',
            old_name='api_pagecha_message_idx',
        ),
    ]
