# Generated by Django 5.2.8 on 2026-05-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_rename_api_pagecha_message_idx_api_pagecha_message_05643b_idx'),
        ('api', '0067_postmedia_width_height'),
    ]

    operations = [
    ]
