# Generated by Django 5.2.8 on 2026-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_activity_comment_scroll_choice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='api_activit_session_53130e_idx',
            old_name='api_activit_session_idx',
        ),
        migrations.RenameIndex(
            model_name='notinterested',
            new_name='api_notinte_user_id_42a541_idx',
            old_name='api_notint_user_kind_idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
