# Generated by Django 5.2.14 on 2026-05-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_pinnedpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
