# Generated by Django 5.2.8 on 2026-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_postmedia_placeholder_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='hls_master',
            field=models.FileField(blank=True, null=True, upload_to='hls/'),
        ),
    ]
