# Generated by Django 5.2 on 2026-06-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_post_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_approved', 'Follow Approved'), ('like', 'Like'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('comment_like', 'Comment Like'), ('mention', 'Mention'), ('post_tag', 'Post Tag'), ('page_invite', 'Page Invite'), ('page_follow', 'Page Follow'), ('page_follow_request', 'Page Follow Request'), ('page_follow_approved', 'Page Follow Approved'), ('page_poster_added', 'Page Poster Added'), ('page_deleted', 'Page Deleted')], max_length=30),
        ),
    ]
