from django.contrib import admin
from .models import Activity, Media,PageInvite, MessageReaction, ProfileVisit, ConversationHidden, PagePoster, MutedPage, PageReport, UserReport, Memory, MutedUser, BlockedUser, PostReport, PostLike, SavedPost, CommentLike, Post, PostMedia, PostMediaTag, Comment, CommentMention, Conversation, Message, Follow, Device, FollowRequest, Notification, UserProfile, Page, PageFollow, PageFollowRequest

admin.site.register(Activity)
admin.site.register(Media)
admin.site.register(Follow)
admin.site.register(Device)
admin.site.register(FollowRequest)
admin.site.register(Notification)
admin.site.register(UserProfile)
admin.site.register(Page)
admin.site.register(PageInvite)
admin.site.register(Memory)
admin.site.register(PageFollow)
admin.site.register(PageFollowRequest)
admin.site.register(Conversation)
admin.site.register(Message)
admin.site.register(MessageReaction)
admin.site.register(Comment)
admin.site.register(CommentMention)
admin.site.register(Post)
admin.site.register(PostMedia)
admin.site.register(PostMediaTag)
admin.site.register(PostLike)
admin.site.register(SavedPost)
admin.site.register(CommentLike)
admin.site.register(PostReport)
admin.site.register(MutedUser)
admin.site.register(BlockedUser)
admin.site.register(UserReport)
admin.site.register(PageReport)
admin.site.register(MutedPage)
admin.site.register(PagePoster)
admin.site.register(ConversationHidden)
admin.site.register(ProfileVisit)
